name: Build and Deploy Vue App to reg.ru Hosting and Handle 401 Errors

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 🧱 Install dependencies
        run: npm install

      - name: 🏗️ Build Vue.js app
        run: npm run build

      - name: ✨ Create .htaccess file
        run: |
          echo "<IfModule mod_rewrite.c>" > dist/.htaccess
          echo "RewriteEngine On" >> dist/.htaccess
          echo "RewriteBase /" >> dist/.htaccess
          echo "RewriteCond %{REQUEST_FILENAME} !-f" >> dist/.htaccess
          echo "RewriteCond %{REQUEST_FILENAME} !-d" >> dist/.htaccess
          echo "RewriteRule ^.*$ index.html [L]" >> dist/.htaccess
          echo "</IfModule>" >> dist/.htaccess

      - name: 🚀 FTP Deploy to reg.ru hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          remote-dir: /public_html/public/